name: Build and Deploy Code

on: [push]

jobs:
  job1: 
    runs-on: ubuntu-20.04

    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: Hello Geraud
        run: echo "Hello Geraud"
